# Generated by Django 5.0.11 on 2025-02-07 00:58
import uuid
from django.db import migrations
from django.db.models import Q


def fill_missing_hashes(apps, schema_editor):

    MapLinkedFile = apps.get_model("sss_maps", "MapLinkedFile")
    for row in MapLinkedFile.objects.filter(Q(hash__isnull=True)|Q(hash='')):
        row.hash = uuid.uuid4()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sss_maps', '0002_maplinkedfile_extension_maplinkedfile_hash'),
    ]

    operations = [
        migrations.RunPython(fill_missing_hashes),
    ]
