# Generated by Django 5.0.11 on 2025-02-07 00:49
import sss_maps.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sss_maps', '0003_populate_hash_20250207_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplinkedfile',
            name='hash',
            field=models.CharField(default=sss_maps.models.get_unique_id, max_length=500, unique=True),
        ),
    ]
